version: "3.9"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=177013
      - MYSQL_DATABASE=pcmatrix
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: